spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cache:
    type: caffeine
    cache-names: jsonFileCache
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1m